language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: peter@superlativecode.com
  api_key:
    secure: 5Md3bKjAWYG9/7yChgv5HZRt4kRP/wSVcPHwCvDso9fH6FBGMCc/wncWeSzYiFC1Nu5dG2WmCoLn47BT0sA+1Ve0fWqyOKYDtad7//gKtwq9h7VQ8dDTlpWOV+SDVEueJL1x4SLqeOOCciZxsjTJjRHXvwTwnwyL9L0EHqUxoKDovjhZjie4IHGhj9XmvWzKkbReSsllRkAjmzR44ZBovXwTS5TKFo9q1dDrAY7HCHqPXs0uceyOlOzkDG7ZWEMcFtJHJF6ZVwHMcaurJ9mSjLNROqjUUBPeyz5O2LqHBbQORGkJd8UdXlIrq77HtrUI7YMlxA9R1SqEBUNGqrLhbky4FaZlU1+XCpcGqz++qH5e1fvfOrmzS17dTlrXq/RpzRyoSbwond6KsLIQUnvB7fo9tEOHlmZ8oIbKa8Z+aypSrYJl+yMF0OnvI1uhvlAQ5HNYYAOlon+1dsYmsCvOcpU1g2HCM42Eep40UGI5sv+OpZdaaJWe2jp+E6SZO5xKjMp4LfGzGsDEFxTJx0ysfbwe2xfTmZ5gUqC5oSWit7hjBxqT3jEV54dRubJP5O7fP8+z438rBtJ1fLgUMwL2nDxEfU52MOXkhmZon4EQKPIhyPy/TOjnOb5poUqKFPsCKQrU1W3beIF3oB/RNS8NM223k+sgrFda6T+EH7uHyoU=
  on:
    tags: true
    repo: peterdemartini/virtual-steak-cooker
